/********************************************************************************
** Form generated from reading UI file 'ventanainicio.ui'
**
** Created by: Qt User Interface Compiler version 5.15.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_VENTANAINICIO_H
#define UI_VENTANAINICIO_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_VentanaInicio
{
public:
    QFrame *panel;
    QTextEdit *textEditComandos;
    QTextEdit *textEditInfo;
    QPushButton *buttonLeer;
    QLabel *labelTronco;
    QLabel *labelRama1;
    QLabel *labelRama2;
    QLabel *labelRama3;
    QLabel *labelRama4;
    QLabel *labelRama5;
    QLabel *labelRama6;
    QLabel *labelRama7;
    QLabel *labelRama8;
    QLabel *labelRama9;
    QLabel *labelRama10;
    QPushButton *pushButton;
    QLabel *label_R10_h3;
    QLabel *label_R10_h5;
    QLabel *label_R10_h7;
    QLabel *label_R10_h1;
    QLabel *label_R10_h9;
    QLabel *label_R10_h8;
    QLabel *label_R10_h4;
    QLabel *label_R10_h10;
    QLabel *label_R10_h6;
    QLabel *label_R10_h2;
    QLabel *label_R9_h9;
    QLabel *label_R9_h3;
    QLabel *label_R9_h5;
    QLabel *label_R9_h4;
    QLabel *label_R9_h7;
    QLabel *label_R9_h2;
    QLabel *label_R9_h8;
    QLabel *label_R9_h6;
    QLabel *label_R9_h10;
    QLabel *label_R9_h1;
    QLabel *label_R8_h2;
    QLabel *label_R8_h8;
    QLabel *label_R8_h6;
    QLabel *label_R8_h7;
    QLabel *label_R8_h4;
    QLabel *label_R8_h9;
    QLabel *label_R8_h3;
    QLabel *label_R8_h5;
    QLabel *label_R8_h1;
    QLabel *label_R8_h10;
    QLabel *label_R7_h9;
    QLabel *label_R7_h3;
    QLabel *label_R7_h5;
    QLabel *label_R7_h4;
    QLabel *label_R7_h7;
    QLabel *label_R7_h2;
    QLabel *label_R7_h8;
    QLabel *label_R7_h6;
    QLabel *label_R7_h10;
    QLabel *label_R7_h1;
    QLabel *label_R6_h2;
    QLabel *label_R6_h8;
    QLabel *label_R6_h6;
    QLabel *label_R6_h7;
    QLabel *label_R6_h4;
    QLabel *label_R6_h9;
    QLabel *label_R6_h3;
    QLabel *label_R6_h5;
    QLabel *label_R6_h1;
    QLabel *label_R6_h10;
    QLabel *label_R5_h9;
    QLabel *label_R5_h3;
    QLabel *label_R5_h5;
    QLabel *label_R5_h4;
    QLabel *label_R5_h7;
    QLabel *label_R5_h2;
    QLabel *label_R5_h8;
    QLabel *label_R5_h6;
    QLabel *label_R5_h10;
    QLabel *label_R5_h1;
    QLabel *label_R4_h2;
    QLabel *label_R4_h8;
    QLabel *label_R4_h6;
    QLabel *label_R4_h7;
    QLabel *label_R4_h4;
    QLabel *label_R4_h9;
    QLabel *label_R4_h3;
    QLabel *label_R4_h5;
    QLabel *label_R4_h1;
    QLabel *label_R4_h10;
    QLabel *label_R3_h9;
    QLabel *label_R3_h3;
    QLabel *label_R3_h5;
    QLabel *label_R3_h4;
    QLabel *label_R3_h7;
    QLabel *label_R3_h2;
    QLabel *label_R3_h8;
    QLabel *label_R3_h6;
    QLabel *label_R3_h10;
    QLabel *label_R3_h1;
    QLabel *label_R2_h2;
    QLabel *label_R2_h8;
    QLabel *label_R2_h6;
    QLabel *label_R2_h7;
    QLabel *label_R2_h4;
    QLabel *label_R2_h9;
    QLabel *label_R2_h3;
    QLabel *label_R2_h5;
    QLabel *label_R2_h1;
    QLabel *label_R2_h10;
    QLabel *label_R1_h9;
    QLabel *label_R1_h3;
    QLabel *label_R1_h5;
    QLabel *label_R1_h4;
    QLabel *label_R1_h7;
    QLabel *label_R1_h2;
    QLabel *label_R1_h8;
    QLabel *label_R1_h6;
    QLabel *label_R1_h10;
    QLabel *label_R1_h1;

    void setupUi(QWidget *VentanaInicio)
    {
        if (VentanaInicio->objectName().isEmpty())
            VentanaInicio->setObjectName(QString::fromUtf8("VentanaInicio"));
        VentanaInicio->resize(1109, 680);
        VentanaInicio->setLayoutDirection(Qt::LeftToRight);
        panel = new QFrame(VentanaInicio);
        panel->setObjectName(QString::fromUtf8("panel"));
        panel->setGeometry(QRect(0, 10, 1111, 681));
        panel->setFrameShape(QFrame::StyledPanel);
        panel->setFrameShadow(QFrame::Raised);
        textEditComandos = new QTextEdit(panel);
        textEditComandos->setObjectName(QString::fromUtf8("textEditComandos"));
        textEditComandos->setGeometry(QRect(0, 580, 871, 61));
        QFont font;
        font.setPointSize(24);
        textEditComandos->setFont(font);
        textEditInfo = new QTextEdit(panel);
        textEditInfo->setObjectName(QString::fromUtf8("textEditInfo"));
        textEditInfo->setEnabled(true);
        textEditInfo->setGeometry(QRect(870, 0, 241, 551));
        buttonLeer = new QPushButton(panel);
        buttonLeer->setObjectName(QString::fromUtf8("buttonLeer"));
        buttonLeer->setGeometry(QRect(880, 600, 88, 34));
        labelTronco = new QLabel(panel);
        labelTronco->setObjectName(QString::fromUtf8("labelTronco"));
        labelTronco->setGeometry(QRect(420, 40, 21, 501));
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(170, 170, 0, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(255, 255, 0, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(212, 212, 0, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(85, 85, 0, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(113, 113, 0, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        QBrush brush6(QColor(255, 255, 255, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush7(QColor(212, 212, 127, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush7);
        QBrush brush8(QColor(255, 255, 220, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        QBrush brush9(QColor(0, 0, 0, 128));
        brush9.setStyle(Qt::SolidPattern);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette::Active, QPalette::PlaceholderText, brush9);
#endif
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush7);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush9);
#endif
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush9);
#endif
        labelTronco->setPalette(palette);
        labelTronco->setStyleSheet(QString::fromUtf8("background-color: rgb(170, 170, 0);"));
        labelRama1 = new QLabel(panel);
        labelRama1->setObjectName(QString::fromUtf8("labelRama1"));
        labelRama1->setGeometry(QRect(100, 60, 321, 16));
        QFont font1;
        font1.setPointSize(6);
        labelRama1->setFont(font1);
        labelRama1->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 170, 127);"));
        labelRama2 = new QLabel(panel);
        labelRama2->setObjectName(QString::fromUtf8("labelRama2"));
        labelRama2->setGeometry(QRect(440, 100, 321, 16));
        labelRama2->setFont(font1);
        labelRama2->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 170, 127);"));
        labelRama3 = new QLabel(panel);
        labelRama3->setObjectName(QString::fromUtf8("labelRama3"));
        labelRama3->setGeometry(QRect(100, 150, 321, 16));
        labelRama3->setFont(font1);
        labelRama3->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 170, 127);"));
        labelRama4 = new QLabel(panel);
        labelRama4->setObjectName(QString::fromUtf8("labelRama4"));
        labelRama4->setGeometry(QRect(440, 190, 321, 16));
        labelRama4->setFont(font1);
        labelRama4->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 170, 127);"));
        labelRama5 = new QLabel(panel);
        labelRama5->setObjectName(QString::fromUtf8("labelRama5"));
        labelRama5->setGeometry(QRect(100, 240, 321, 16));
        labelRama5->setFont(font1);
        labelRama5->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 170, 127);"));
        labelRama6 = new QLabel(panel);
        labelRama6->setObjectName(QString::fromUtf8("labelRama6"));
        labelRama6->setGeometry(QRect(440, 280, 321, 16));
        labelRama6->setFont(font1);
        labelRama6->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 170, 127);"));
        labelRama7 = new QLabel(panel);
        labelRama7->setObjectName(QString::fromUtf8("labelRama7"));
        labelRama7->setGeometry(QRect(100, 330, 321, 16));
        labelRama7->setFont(font1);
        labelRama7->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 170, 127);"));
        labelRama8 = new QLabel(panel);
        labelRama8->setObjectName(QString::fromUtf8("labelRama8"));
        labelRama8->setGeometry(QRect(440, 370, 321, 16));
        labelRama8->setFont(font1);
        labelRama8->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 170, 127);"));
        labelRama9 = new QLabel(panel);
        labelRama9->setObjectName(QString::fromUtf8("labelRama9"));
        labelRama9->setGeometry(QRect(100, 410, 321, 16));
        labelRama9->setFont(font1);
        labelRama9->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 170, 127);"));
        labelRama10 = new QLabel(panel);
        labelRama10->setObjectName(QString::fromUtf8("labelRama10"));
        labelRama10->setGeometry(QRect(440, 450, 321, 16));
        labelRama10->setFont(font1);
        labelRama10->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 170, 127);"));
        pushButton = new QPushButton(panel);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(1010, 560, 88, 34));
        label_R10_h3 = new QLabel(panel);
        label_R10_h3->setObjectName(QString::fromUtf8("label_R10_h3"));
        label_R10_h3->setGeometry(QRect(670, 440, 16, 16));
        label_R10_h3->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R10_h5 = new QLabel(panel);
        label_R10_h5->setObjectName(QString::fromUtf8("label_R10_h5"));
        label_R10_h5->setGeometry(QRect(620, 440, 16, 16));
        label_R10_h5->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R10_h7 = new QLabel(panel);
        label_R10_h7->setObjectName(QString::fromUtf8("label_R10_h7"));
        label_R10_h7->setGeometry(QRect(570, 440, 16, 16));
        label_R10_h7->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R10_h1 = new QLabel(panel);
        label_R10_h1->setObjectName(QString::fromUtf8("label_R10_h1"));
        label_R10_h1->setGeometry(QRect(730, 440, 16, 16));
        label_R10_h1->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R10_h9 = new QLabel(panel);
        label_R10_h9->setObjectName(QString::fromUtf8("label_R10_h9"));
        label_R10_h9->setGeometry(QRect(520, 440, 16, 16));
        label_R10_h9->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R10_h8 = new QLabel(panel);
        label_R10_h8->setObjectName(QString::fromUtf8("label_R10_h8"));
        label_R10_h8->setGeometry(QRect(540, 460, 16, 16));
        label_R10_h8->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R10_h4 = new QLabel(panel);
        label_R10_h4->setObjectName(QString::fromUtf8("label_R10_h4"));
        label_R10_h4->setGeometry(QRect(640, 460, 16, 16));
        label_R10_h4->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R10_h10 = new QLabel(panel);
        label_R10_h10->setObjectName(QString::fromUtf8("label_R10_h10"));
        label_R10_h10->setGeometry(QRect(490, 460, 16, 16));
        label_R10_h10->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R10_h6 = new QLabel(panel);
        label_R10_h6->setObjectName(QString::fromUtf8("label_R10_h6"));
        label_R10_h6->setGeometry(QRect(590, 460, 16, 16));
        label_R10_h6->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R10_h2 = new QLabel(panel);
        label_R10_h2->setObjectName(QString::fromUtf8("label_R10_h2"));
        label_R10_h2->setGeometry(QRect(700, 460, 16, 16));
        label_R10_h2->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R9_h9 = new QLabel(panel);
        label_R9_h9->setObjectName(QString::fromUtf8("label_R9_h9"));
        label_R9_h9->setGeometry(QRect(330, 420, 16, 16));
        label_R9_h9->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R9_h3 = new QLabel(panel);
        label_R9_h3->setObjectName(QString::fromUtf8("label_R9_h3"));
        label_R9_h3->setGeometry(QRect(170, 420, 16, 16));
        label_R9_h3->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R9_h5 = new QLabel(panel);
        label_R9_h5->setObjectName(QString::fromUtf8("label_R9_h5"));
        label_R9_h5->setGeometry(QRect(220, 420, 16, 16));
        label_R9_h5->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R9_h4 = new QLabel(panel);
        label_R9_h4->setObjectName(QString::fromUtf8("label_R9_h4"));
        label_R9_h4->setGeometry(QRect(200, 400, 16, 16));
        label_R9_h4->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R9_h7 = new QLabel(panel);
        label_R9_h7->setObjectName(QString::fromUtf8("label_R9_h7"));
        label_R9_h7->setGeometry(QRect(270, 420, 16, 16));
        label_R9_h7->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R9_h2 = new QLabel(panel);
        label_R9_h2->setObjectName(QString::fromUtf8("label_R9_h2"));
        label_R9_h2->setGeometry(QRect(150, 400, 16, 16));
        label_R9_h2->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R9_h8 = new QLabel(panel);
        label_R9_h8->setObjectName(QString::fromUtf8("label_R9_h8"));
        label_R9_h8->setGeometry(QRect(300, 400, 16, 16));
        label_R9_h8->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R9_h6 = new QLabel(panel);
        label_R9_h6->setObjectName(QString::fromUtf8("label_R9_h6"));
        label_R9_h6->setGeometry(QRect(250, 400, 16, 16));
        label_R9_h6->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R9_h10 = new QLabel(panel);
        label_R9_h10->setObjectName(QString::fromUtf8("label_R9_h10"));
        label_R9_h10->setGeometry(QRect(360, 400, 16, 16));
        label_R9_h10->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R9_h1 = new QLabel(panel);
        label_R9_h1->setObjectName(QString::fromUtf8("label_R9_h1"));
        label_R9_h1->setGeometry(QRect(120, 420, 16, 16));
        label_R9_h1->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R8_h2 = new QLabel(panel);
        label_R8_h2->setObjectName(QString::fromUtf8("label_R8_h2"));
        label_R8_h2->setGeometry(QRect(690, 380, 16, 16));
        label_R8_h2->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R8_h8 = new QLabel(panel);
        label_R8_h8->setObjectName(QString::fromUtf8("label_R8_h8"));
        label_R8_h8->setGeometry(QRect(530, 380, 16, 16));
        label_R8_h8->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R8_h6 = new QLabel(panel);
        label_R8_h6->setObjectName(QString::fromUtf8("label_R8_h6"));
        label_R8_h6->setGeometry(QRect(580, 380, 16, 16));
        label_R8_h6->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R8_h7 = new QLabel(panel);
        label_R8_h7->setObjectName(QString::fromUtf8("label_R8_h7"));
        label_R8_h7->setGeometry(QRect(560, 360, 16, 16));
        label_R8_h7->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R8_h4 = new QLabel(panel);
        label_R8_h4->setObjectName(QString::fromUtf8("label_R8_h4"));
        label_R8_h4->setGeometry(QRect(630, 380, 16, 16));
        label_R8_h4->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R8_h9 = new QLabel(panel);
        label_R8_h9->setObjectName(QString::fromUtf8("label_R8_h9"));
        label_R8_h9->setGeometry(QRect(510, 360, 16, 16));
        label_R8_h9->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R8_h3 = new QLabel(panel);
        label_R8_h3->setObjectName(QString::fromUtf8("label_R8_h3"));
        label_R8_h3->setGeometry(QRect(660, 360, 16, 16));
        label_R8_h3->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R8_h5 = new QLabel(panel);
        label_R8_h5->setObjectName(QString::fromUtf8("label_R8_h5"));
        label_R8_h5->setGeometry(QRect(610, 360, 16, 16));
        label_R8_h5->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R8_h1 = new QLabel(panel);
        label_R8_h1->setObjectName(QString::fromUtf8("label_R8_h1"));
        label_R8_h1->setGeometry(QRect(720, 360, 16, 16));
        label_R8_h1->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R8_h10 = new QLabel(panel);
        label_R8_h10->setObjectName(QString::fromUtf8("label_R8_h10"));
        label_R8_h10->setGeometry(QRect(480, 380, 16, 16));
        label_R8_h10->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R7_h9 = new QLabel(panel);
        label_R7_h9->setObjectName(QString::fromUtf8("label_R7_h9"));
        label_R7_h9->setGeometry(QRect(340, 340, 16, 16));
        label_R7_h9->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R7_h3 = new QLabel(panel);
        label_R7_h3->setObjectName(QString::fromUtf8("label_R7_h3"));
        label_R7_h3->setGeometry(QRect(180, 340, 16, 16));
        label_R7_h3->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R7_h5 = new QLabel(panel);
        label_R7_h5->setObjectName(QString::fromUtf8("label_R7_h5"));
        label_R7_h5->setGeometry(QRect(230, 340, 16, 16));
        label_R7_h5->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R7_h4 = new QLabel(panel);
        label_R7_h4->setObjectName(QString::fromUtf8("label_R7_h4"));
        label_R7_h4->setGeometry(QRect(210, 320, 16, 16));
        label_R7_h4->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R7_h7 = new QLabel(panel);
        label_R7_h7->setObjectName(QString::fromUtf8("label_R7_h7"));
        label_R7_h7->setGeometry(QRect(280, 340, 16, 16));
        label_R7_h7->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R7_h2 = new QLabel(panel);
        label_R7_h2->setObjectName(QString::fromUtf8("label_R7_h2"));
        label_R7_h2->setGeometry(QRect(160, 320, 16, 16));
        label_R7_h2->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R7_h8 = new QLabel(panel);
        label_R7_h8->setObjectName(QString::fromUtf8("label_R7_h8"));
        label_R7_h8->setGeometry(QRect(310, 320, 16, 16));
        label_R7_h8->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R7_h6 = new QLabel(panel);
        label_R7_h6->setObjectName(QString::fromUtf8("label_R7_h6"));
        label_R7_h6->setGeometry(QRect(260, 320, 16, 16));
        label_R7_h6->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R7_h10 = new QLabel(panel);
        label_R7_h10->setObjectName(QString::fromUtf8("label_R7_h10"));
        label_R7_h10->setGeometry(QRect(370, 320, 16, 16));
        label_R7_h10->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R7_h1 = new QLabel(panel);
        label_R7_h1->setObjectName(QString::fromUtf8("label_R7_h1"));
        label_R7_h1->setGeometry(QRect(130, 340, 16, 16));
        label_R7_h1->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R6_h2 = new QLabel(panel);
        label_R6_h2->setObjectName(QString::fromUtf8("label_R6_h2"));
        label_R6_h2->setGeometry(QRect(690, 290, 16, 16));
        label_R6_h2->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R6_h8 = new QLabel(panel);
        label_R6_h8->setObjectName(QString::fromUtf8("label_R6_h8"));
        label_R6_h8->setGeometry(QRect(530, 290, 16, 16));
        label_R6_h8->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R6_h6 = new QLabel(panel);
        label_R6_h6->setObjectName(QString::fromUtf8("label_R6_h6"));
        label_R6_h6->setGeometry(QRect(580, 290, 16, 16));
        label_R6_h6->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R6_h7 = new QLabel(panel);
        label_R6_h7->setObjectName(QString::fromUtf8("label_R6_h7"));
        label_R6_h7->setGeometry(QRect(560, 270, 16, 16));
        label_R6_h7->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R6_h4 = new QLabel(panel);
        label_R6_h4->setObjectName(QString::fromUtf8("label_R6_h4"));
        label_R6_h4->setGeometry(QRect(630, 290, 16, 16));
        label_R6_h4->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R6_h9 = new QLabel(panel);
        label_R6_h9->setObjectName(QString::fromUtf8("label_R6_h9"));
        label_R6_h9->setGeometry(QRect(510, 270, 16, 16));
        label_R6_h9->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R6_h3 = new QLabel(panel);
        label_R6_h3->setObjectName(QString::fromUtf8("label_R6_h3"));
        label_R6_h3->setGeometry(QRect(660, 270, 16, 16));
        label_R6_h3->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R6_h5 = new QLabel(panel);
        label_R6_h5->setObjectName(QString::fromUtf8("label_R6_h5"));
        label_R6_h5->setGeometry(QRect(610, 270, 16, 16));
        label_R6_h5->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R6_h1 = new QLabel(panel);
        label_R6_h1->setObjectName(QString::fromUtf8("label_R6_h1"));
        label_R6_h1->setGeometry(QRect(720, 270, 16, 16));
        label_R6_h1->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R6_h10 = new QLabel(panel);
        label_R6_h10->setObjectName(QString::fromUtf8("label_R6_h10"));
        label_R6_h10->setGeometry(QRect(480, 290, 16, 16));
        label_R6_h10->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R5_h9 = new QLabel(panel);
        label_R5_h9->setObjectName(QString::fromUtf8("label_R5_h9"));
        label_R5_h9->setGeometry(QRect(340, 250, 16, 16));
        label_R5_h9->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R5_h3 = new QLabel(panel);
        label_R5_h3->setObjectName(QString::fromUtf8("label_R5_h3"));
        label_R5_h3->setGeometry(QRect(180, 250, 16, 16));
        label_R5_h3->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R5_h5 = new QLabel(panel);
        label_R5_h5->setObjectName(QString::fromUtf8("label_R5_h5"));
        label_R5_h5->setGeometry(QRect(230, 250, 16, 16));
        label_R5_h5->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R5_h4 = new QLabel(panel);
        label_R5_h4->setObjectName(QString::fromUtf8("label_R5_h4"));
        label_R5_h4->setGeometry(QRect(210, 230, 16, 16));
        label_R5_h4->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R5_h7 = new QLabel(panel);
        label_R5_h7->setObjectName(QString::fromUtf8("label_R5_h7"));
        label_R5_h7->setGeometry(QRect(280, 250, 16, 16));
        label_R5_h7->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R5_h2 = new QLabel(panel);
        label_R5_h2->setObjectName(QString::fromUtf8("label_R5_h2"));
        label_R5_h2->setGeometry(QRect(160, 230, 16, 16));
        label_R5_h2->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R5_h8 = new QLabel(panel);
        label_R5_h8->setObjectName(QString::fromUtf8("label_R5_h8"));
        label_R5_h8->setGeometry(QRect(310, 230, 16, 16));
        label_R5_h8->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R5_h6 = new QLabel(panel);
        label_R5_h6->setObjectName(QString::fromUtf8("label_R5_h6"));
        label_R5_h6->setGeometry(QRect(260, 230, 16, 16));
        label_R5_h6->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R5_h10 = new QLabel(panel);
        label_R5_h10->setObjectName(QString::fromUtf8("label_R5_h10"));
        label_R5_h10->setGeometry(QRect(370, 230, 16, 16));
        label_R5_h10->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R5_h1 = new QLabel(panel);
        label_R5_h1->setObjectName(QString::fromUtf8("label_R5_h1"));
        label_R5_h1->setGeometry(QRect(130, 250, 16, 16));
        label_R5_h1->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R4_h2 = new QLabel(panel);
        label_R4_h2->setObjectName(QString::fromUtf8("label_R4_h2"));
        label_R4_h2->setGeometry(QRect(690, 200, 16, 16));
        label_R4_h2->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R4_h8 = new QLabel(panel);
        label_R4_h8->setObjectName(QString::fromUtf8("label_R4_h8"));
        label_R4_h8->setGeometry(QRect(530, 200, 16, 16));
        label_R4_h8->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R4_h6 = new QLabel(panel);
        label_R4_h6->setObjectName(QString::fromUtf8("label_R4_h6"));
        label_R4_h6->setGeometry(QRect(580, 200, 16, 16));
        label_R4_h6->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R4_h7 = new QLabel(panel);
        label_R4_h7->setObjectName(QString::fromUtf8("label_R4_h7"));
        label_R4_h7->setGeometry(QRect(560, 180, 16, 16));
        label_R4_h7->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R4_h4 = new QLabel(panel);
        label_R4_h4->setObjectName(QString::fromUtf8("label_R4_h4"));
        label_R4_h4->setGeometry(QRect(630, 200, 16, 16));
        label_R4_h4->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R4_h9 = new QLabel(panel);
        label_R4_h9->setObjectName(QString::fromUtf8("label_R4_h9"));
        label_R4_h9->setGeometry(QRect(510, 180, 16, 16));
        label_R4_h9->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R4_h3 = new QLabel(panel);
        label_R4_h3->setObjectName(QString::fromUtf8("label_R4_h3"));
        label_R4_h3->setGeometry(QRect(660, 180, 16, 16));
        label_R4_h3->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R4_h5 = new QLabel(panel);
        label_R4_h5->setObjectName(QString::fromUtf8("label_R4_h5"));
        label_R4_h5->setGeometry(QRect(610, 180, 16, 16));
        label_R4_h5->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R4_h1 = new QLabel(panel);
        label_R4_h1->setObjectName(QString::fromUtf8("label_R4_h1"));
        label_R4_h1->setGeometry(QRect(720, 180, 16, 16));
        label_R4_h1->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R4_h10 = new QLabel(panel);
        label_R4_h10->setObjectName(QString::fromUtf8("label_R4_h10"));
        label_R4_h10->setGeometry(QRect(480, 200, 16, 16));
        label_R4_h10->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R3_h9 = new QLabel(panel);
        label_R3_h9->setObjectName(QString::fromUtf8("label_R3_h9"));
        label_R3_h9->setGeometry(QRect(340, 160, 16, 16));
        label_R3_h9->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R3_h3 = new QLabel(panel);
        label_R3_h3->setObjectName(QString::fromUtf8("label_R3_h3"));
        label_R3_h3->setGeometry(QRect(180, 160, 16, 16));
        label_R3_h3->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R3_h5 = new QLabel(panel);
        label_R3_h5->setObjectName(QString::fromUtf8("label_R3_h5"));
        label_R3_h5->setGeometry(QRect(230, 160, 16, 16));
        label_R3_h5->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R3_h4 = new QLabel(panel);
        label_R3_h4->setObjectName(QString::fromUtf8("label_R3_h4"));
        label_R3_h4->setGeometry(QRect(210, 140, 16, 16));
        label_R3_h4->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R3_h7 = new QLabel(panel);
        label_R3_h7->setObjectName(QString::fromUtf8("label_R3_h7"));
        label_R3_h7->setGeometry(QRect(280, 160, 16, 16));
        label_R3_h7->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R3_h2 = new QLabel(panel);
        label_R3_h2->setObjectName(QString::fromUtf8("label_R3_h2"));
        label_R3_h2->setGeometry(QRect(160, 140, 16, 16));
        label_R3_h2->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R3_h8 = new QLabel(panel);
        label_R3_h8->setObjectName(QString::fromUtf8("label_R3_h8"));
        label_R3_h8->setGeometry(QRect(310, 140, 16, 16));
        label_R3_h8->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R3_h6 = new QLabel(panel);
        label_R3_h6->setObjectName(QString::fromUtf8("label_R3_h6"));
        label_R3_h6->setGeometry(QRect(260, 140, 16, 16));
        label_R3_h6->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R3_h10 = new QLabel(panel);
        label_R3_h10->setObjectName(QString::fromUtf8("label_R3_h10"));
        label_R3_h10->setGeometry(QRect(370, 140, 16, 16));
        label_R3_h10->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R3_h1 = new QLabel(panel);
        label_R3_h1->setObjectName(QString::fromUtf8("label_R3_h1"));
        label_R3_h1->setGeometry(QRect(130, 160, 16, 16));
        label_R3_h1->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R2_h2 = new QLabel(panel);
        label_R2_h2->setObjectName(QString::fromUtf8("label_R2_h2"));
        label_R2_h2->setGeometry(QRect(690, 110, 16, 16));
        label_R2_h2->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R2_h8 = new QLabel(panel);
        label_R2_h8->setObjectName(QString::fromUtf8("label_R2_h8"));
        label_R2_h8->setGeometry(QRect(530, 110, 16, 16));
        label_R2_h8->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R2_h6 = new QLabel(panel);
        label_R2_h6->setObjectName(QString::fromUtf8("label_R2_h6"));
        label_R2_h6->setGeometry(QRect(580, 110, 16, 16));
        label_R2_h6->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R2_h7 = new QLabel(panel);
        label_R2_h7->setObjectName(QString::fromUtf8("label_R2_h7"));
        label_R2_h7->setGeometry(QRect(560, 90, 16, 16));
        label_R2_h7->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R2_h4 = new QLabel(panel);
        label_R2_h4->setObjectName(QString::fromUtf8("label_R2_h4"));
        label_R2_h4->setGeometry(QRect(630, 110, 16, 16));
        label_R2_h4->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R2_h9 = new QLabel(panel);
        label_R2_h9->setObjectName(QString::fromUtf8("label_R2_h9"));
        label_R2_h9->setGeometry(QRect(510, 90, 16, 16));
        label_R2_h9->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R2_h3 = new QLabel(panel);
        label_R2_h3->setObjectName(QString::fromUtf8("label_R2_h3"));
        label_R2_h3->setGeometry(QRect(660, 90, 16, 16));
        label_R2_h3->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R2_h5 = new QLabel(panel);
        label_R2_h5->setObjectName(QString::fromUtf8("label_R2_h5"));
        label_R2_h5->setGeometry(QRect(610, 90, 16, 16));
        label_R2_h5->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R2_h1 = new QLabel(panel);
        label_R2_h1->setObjectName(QString::fromUtf8("label_R2_h1"));
        label_R2_h1->setGeometry(QRect(720, 90, 16, 16));
        label_R2_h1->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R2_h10 = new QLabel(panel);
        label_R2_h10->setObjectName(QString::fromUtf8("label_R2_h10"));
        label_R2_h10->setGeometry(QRect(480, 110, 16, 16));
        label_R2_h10->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R1_h9 = new QLabel(panel);
        label_R1_h9->setObjectName(QString::fromUtf8("label_R1_h9"));
        label_R1_h9->setGeometry(QRect(350, 70, 16, 16));
        label_R1_h9->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R1_h3 = new QLabel(panel);
        label_R1_h3->setObjectName(QString::fromUtf8("label_R1_h3"));
        label_R1_h3->setGeometry(QRect(190, 70, 16, 16));
        label_R1_h3->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R1_h5 = new QLabel(panel);
        label_R1_h5->setObjectName(QString::fromUtf8("label_R1_h5"));
        label_R1_h5->setGeometry(QRect(240, 70, 16, 16));
        label_R1_h5->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R1_h4 = new QLabel(panel);
        label_R1_h4->setObjectName(QString::fromUtf8("label_R1_h4"));
        label_R1_h4->setGeometry(QRect(220, 50, 16, 16));
        label_R1_h4->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R1_h7 = new QLabel(panel);
        label_R1_h7->setObjectName(QString::fromUtf8("label_R1_h7"));
        label_R1_h7->setGeometry(QRect(290, 70, 16, 16));
        label_R1_h7->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R1_h2 = new QLabel(panel);
        label_R1_h2->setObjectName(QString::fromUtf8("label_R1_h2"));
        label_R1_h2->setGeometry(QRect(170, 50, 16, 16));
        label_R1_h2->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R1_h8 = new QLabel(panel);
        label_R1_h8->setObjectName(QString::fromUtf8("label_R1_h8"));
        label_R1_h8->setGeometry(QRect(320, 50, 16, 16));
        label_R1_h8->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R1_h6 = new QLabel(panel);
        label_R1_h6->setObjectName(QString::fromUtf8("label_R1_h6"));
        label_R1_h6->setGeometry(QRect(270, 50, 16, 16));
        label_R1_h6->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R1_h10 = new QLabel(panel);
        label_R1_h10->setObjectName(QString::fromUtf8("label_R1_h10"));
        label_R1_h10->setGeometry(QRect(380, 50, 16, 16));
        label_R1_h10->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));
        label_R1_h1 = new QLabel(panel);
        label_R1_h1->setObjectName(QString::fromUtf8("label_R1_h1"));
        label_R1_h1->setGeometry(QRect(140, 70, 16, 16));
        label_R1_h1->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);"));

        retranslateUi(VentanaInicio);

        QMetaObject::connectSlotsByName(VentanaInicio);
    } // setupUi

    void retranslateUi(QWidget *VentanaInicio)
    {
        VentanaInicio->setWindowTitle(QCoreApplication::translate("VentanaInicio", "VentanaInicio", nullptr));
        textEditComandos->setHtml(QCoreApplication::translate("VentanaInicio", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Noto Sans'; font-size:24pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", nullptr));
        buttonLeer->setText(QCoreApplication::translate("VentanaInicio", "Aplicar", nullptr));
        labelTronco->setText(QString());
        labelRama1->setText(QString());
        labelRama2->setText(QString());
        labelRama3->setText(QString());
        labelRama4->setText(QString());
        labelRama5->setText(QString());
        labelRama6->setText(QString());
        labelRama7->setText(QString());
        labelRama8->setText(QString());
        labelRama9->setText(QString());
        labelRama10->setText(QString());
        pushButton->setText(QCoreApplication::translate("VentanaInicio", "PushButton", nullptr));
        label_R10_h3->setText(QString());
        label_R10_h5->setText(QString());
        label_R10_h7->setText(QString());
        label_R10_h1->setText(QString());
        label_R10_h9->setText(QString());
        label_R10_h8->setText(QString());
        label_R10_h4->setText(QString());
        label_R10_h10->setText(QString());
        label_R10_h6->setText(QString());
        label_R10_h2->setText(QString());
        label_R9_h9->setText(QString());
        label_R9_h3->setText(QString());
        label_R9_h5->setText(QString());
        label_R9_h4->setText(QString());
        label_R9_h7->setText(QString());
        label_R9_h2->setText(QString());
        label_R9_h8->setText(QString());
        label_R9_h6->setText(QString());
        label_R9_h10->setText(QString());
        label_R9_h1->setText(QString());
        label_R8_h2->setText(QString());
        label_R8_h8->setText(QString());
        label_R8_h6->setText(QString());
        label_R8_h7->setText(QString());
        label_R8_h4->setText(QString());
        label_R8_h9->setText(QString());
        label_R8_h3->setText(QString());
        label_R8_h5->setText(QString());
        label_R8_h1->setText(QString());
        label_R8_h10->setText(QString());
        label_R7_h9->setText(QString());
        label_R7_h3->setText(QString());
        label_R7_h5->setText(QString());
        label_R7_h4->setText(QString());
        label_R7_h7->setText(QString());
        label_R7_h2->setText(QString());
        label_R7_h8->setText(QString());
        label_R7_h6->setText(QString());
        label_R7_h10->setText(QString());
        label_R7_h1->setText(QString());
        label_R6_h2->setText(QString());
        label_R6_h8->setText(QString());
        label_R6_h6->setText(QString());
        label_R6_h7->setText(QString());
        label_R6_h4->setText(QString());
        label_R6_h9->setText(QString());
        label_R6_h3->setText(QString());
        label_R6_h5->setText(QString());
        label_R6_h1->setText(QString());
        label_R6_h10->setText(QString());
        label_R5_h9->setText(QString());
        label_R5_h3->setText(QString());
        label_R5_h5->setText(QString());
        label_R5_h4->setText(QString());
        label_R5_h7->setText(QString());
        label_R5_h2->setText(QString());
        label_R5_h8->setText(QString());
        label_R5_h6->setText(QString());
        label_R5_h10->setText(QString());
        label_R5_h1->setText(QString());
        label_R4_h2->setText(QString());
        label_R4_h8->setText(QString());
        label_R4_h6->setText(QString());
        label_R4_h7->setText(QString());
        label_R4_h4->setText(QString());
        label_R4_h9->setText(QString());
        label_R4_h3->setText(QString());
        label_R4_h5->setText(QString());
        label_R4_h1->setText(QString());
        label_R4_h10->setText(QString());
        label_R3_h9->setText(QString());
        label_R3_h3->setText(QString());
        label_R3_h5->setText(QString());
        label_R3_h4->setText(QString());
        label_R3_h7->setText(QString());
        label_R3_h2->setText(QString());
        label_R3_h8->setText(QString());
        label_R3_h6->setText(QString());
        label_R3_h10->setText(QString());
        label_R3_h1->setText(QString());
        label_R2_h2->setText(QString());
        label_R2_h8->setText(QString());
        label_R2_h6->setText(QString());
        label_R2_h7->setText(QString());
        label_R2_h4->setText(QString());
        label_R2_h9->setText(QString());
        label_R2_h3->setText(QString());
        label_R2_h5->setText(QString());
        label_R2_h1->setText(QString());
        label_R2_h10->setText(QString());
        label_R1_h9->setText(QString());
        label_R1_h3->setText(QString());
        label_R1_h5->setText(QString());
        label_R1_h4->setText(QString());
        label_R1_h7->setText(QString());
        label_R1_h2->setText(QString());
        label_R1_h8->setText(QString());
        label_R1_h6->setText(QString());
        label_R1_h10->setText(QString());
        label_R1_h1->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class VentanaInicio: public Ui_VentanaInicio {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_VENTANAINICIO_H
